development:
  adapter: postgresql
  encoding: unicode
  database: travelblog_development
  host: localhost
  pool: 5
  username: postgres
  password: root
  prepared_statements: false

test:
  adapter: postgresql
  encoding: unicode
  database: travelblog_test
  host: localhost
  pool: 5
  username: postgres
  password: root
  prepared_statements: false

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  prepared_statements: false
