toolbar:
  - styleselect | bold italic | undo redo
  - image | link | media
plugins:
  - image
  - link
  - media
image_class_list: [
    {title: 'None', value: ''},
    {title: 'centre', value: 'center'}
  ]
